global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/aa2dbf37-d8eb-47ec-8139-467ef68d165c'
        send_resolved: false